// RECORDED FROM CHROMIUM — do not hand-edit.
//
// Every row is a real `<input>` in a real browser: type, step and min set as
// content attributes, the value set through the IDL property (see
// record-step-mismatch-table.mjs for why not `setAttribute`), and
// `validity.stepMismatch`, range underflow/overflow, and the post-sanitization
// `input.value` read back out.
//
// `sanitized` is kept because it explains the `mismatch: false` rows that look
// wrong at a glance: a value the type cannot parse is discarded by value
// sanitization before validity is ever consulted, so it is never a step
// mismatch.
//
// Regenerate with apps/a11y/scripts/record-step-mismatch-table.mjs.

export type RecordedStepCase = {
  type: string;
  step: number | string | undefined;
  min: number | string | undefined;
  max: number | string | undefined;
  value: string;
  sanitized: string;
  mismatch: boolean;
  underflow: boolean;
  overflow: boolean;
};

export const recordedStepCases: RecordedStepCase[] = [
  {
    type: 'number',
    step: 5,
    min: undefined,
    max: undefined,
    value: '0',
    sanitized: '0',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: undefined,
    max: undefined,
    value: '5',
    sanitized: '5',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: undefined,
    max: undefined,
    value: '7',
    sanitized: '7',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: undefined,
    max: undefined,
    value: '10',
    sanitized: '10',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: undefined,
    max: undefined,
    value: '-5',
    sanitized: '-5',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: undefined,
    max: undefined,
    value: '-7',
    sanitized: '-7',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: undefined,
    max: undefined,
    value: '2.5',
    sanitized: '2.5',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: undefined,
    max: undefined,
    value: '',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: 1,
    max: undefined,
    value: '1',
    sanitized: '1',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: 1,
    max: undefined,
    value: '6',
    sanitized: '6',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: 1,
    max: undefined,
    value: '11',
    sanitized: '11',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: 1,
    max: undefined,
    value: '0',
    sanitized: '0',
    mismatch: true,
    underflow: true,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: 1,
    max: undefined,
    value: '5',
    sanitized: '5',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: 1,
    max: undefined,
    value: '7',
    sanitized: '7',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 5,
    min: 1,
    max: undefined,
    value: '-4',
    sanitized: '-4',
    mismatch: false,
    underflow: true,
    overflow: false
  },
  {
    type: 'number',
    step: 2,
    min: 1,
    max: undefined,
    value: '1',
    sanitized: '1',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 2,
    min: 1,
    max: undefined,
    value: '2',
    sanitized: '2',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 2,
    min: 1,
    max: undefined,
    value: '3',
    sanitized: '3',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 2,
    min: 1,
    max: undefined,
    value: '4',
    sanitized: '4',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 2,
    min: 1,
    max: undefined,
    value: '-1',
    sanitized: '-1',
    mismatch: false,
    underflow: true,
    overflow: false
  },
  {
    type: 'number',
    step: 0.1,
    min: undefined,
    max: undefined,
    value: '0.1',
    sanitized: '0.1',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.1,
    min: undefined,
    max: undefined,
    value: '0.2',
    sanitized: '0.2',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.1,
    min: undefined,
    max: undefined,
    value: '0.3',
    sanitized: '0.3',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.1,
    min: undefined,
    max: undefined,
    value: '0.30',
    sanitized: '0.30',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.1,
    min: undefined,
    max: undefined,
    value: '0.35',
    sanitized: '0.35',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.1,
    min: undefined,
    max: undefined,
    value: '1',
    sanitized: '1',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.1,
    min: undefined,
    max: undefined,
    value: '1.1',
    sanitized: '1.1',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.1,
    min: undefined,
    max: undefined,
    value: '2.7755575615628914e-17',
    sanitized: '2.7755575615628914e-17',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.01,
    min: undefined,
    max: undefined,
    value: '19.99',
    sanitized: '19.99',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.01,
    min: undefined,
    max: undefined,
    value: '19.999',
    sanitized: '19.999',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.01,
    min: undefined,
    max: undefined,
    value: '0.07',
    sanitized: '0.07',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.01,
    min: undefined,
    max: undefined,
    value: '1',
    sanitized: '1',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.25,
    min: 0.1,
    max: undefined,
    value: '0.1',
    sanitized: '0.1',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.25,
    min: 0.1,
    max: undefined,
    value: '0.35',
    sanitized: '0.35',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.25,
    min: 0.1,
    max: undefined,
    value: '0.6',
    sanitized: '0.6',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0.25,
    min: 0.1,
    max: undefined,
    value: '0.2',
    sanitized: '0.2',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 'any',
    min: undefined,
    max: undefined,
    value: '1.5',
    sanitized: '1.5',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 'any',
    min: undefined,
    max: undefined,
    value: '0.30000001',
    sanitized: '0.30000001',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 'any',
    min: undefined,
    max: undefined,
    value: '7',
    sanitized: '7',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 'any',
    min: undefined,
    max: undefined,
    value: '-3.3',
    sanitized: '-3.3',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 'ANY',
    min: undefined,
    max: undefined,
    value: '1.5',
    sanitized: '1.5',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0,
    min: undefined,
    max: undefined,
    value: '1.5',
    sanitized: '1.5',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 0,
    min: undefined,
    max: undefined,
    value: '2',
    sanitized: '2',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: -5,
    min: undefined,
    max: undefined,
    value: '1.5',
    sanitized: '1.5',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: -5,
    min: undefined,
    max: undefined,
    value: '2',
    sanitized: '2',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: -5,
    min: undefined,
    max: undefined,
    value: '7',
    sanitized: '7',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 'banana',
    min: undefined,
    max: undefined,
    value: '1.5',
    sanitized: '1.5',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 'banana',
    min: undefined,
    max: undefined,
    value: '2',
    sanitized: '2',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 3,
    min: undefined,
    max: undefined,
    value: '1e2',
    sanitized: '1e2',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 3,
    min: undefined,
    max: undefined,
    value: '.5',
    sanitized: '.5',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 3,
    min: undefined,
    max: undefined,
    value: '5.',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 3,
    min: undefined,
    max: undefined,
    value: '0x10',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 3,
    min: undefined,
    max: undefined,
    value: ' 6 ',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 3,
    min: undefined,
    max: undefined,
    value: 'abc',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 3,
    min: undefined,
    max: undefined,
    value: '99999999999999999999',
    sanitized: '99999999999999999999',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 3,
    min: undefined,
    max: undefined,
    value: '9',
    sanitized: '9',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 1,
    min: undefined,
    max: undefined,
    value: '1.5',
    sanitized: '1.5',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 1,
    min: undefined,
    max: undefined,
    value: '2',
    sanitized: '2',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 1,
    min: undefined,
    max: undefined,
    value: '-2',
    sanitized: '-2',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 1,
    min: undefined,
    max: undefined,
    value: '1e21',
    sanitized: '1e21',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 1e-7,
    min: undefined,
    max: undefined,
    value: '0.0000002',
    sanitized: '0.0000002',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 1e-7,
    min: undefined,
    max: undefined,
    value: '0.00000025',
    sanitized: '0.00000025',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 7,
    min: 2,
    max: undefined,
    value: '2',
    sanitized: '2',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 7,
    min: 2,
    max: undefined,
    value: '9',
    sanitized: '9',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 7,
    min: 2,
    max: undefined,
    value: '16',
    sanitized: '16',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 7,
    min: 2,
    max: undefined,
    value: '3',
    sanitized: '3',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'number',
    step: 7,
    min: 2,
    max: undefined,
    value: '-5',
    sanitized: '-5',
    mismatch: false,
    underflow: true,
    overflow: false
  },
  {
    type: 'range',
    step: 5,
    min: undefined,
    max: undefined,
    value: '0',
    sanitized: '0',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'range',
    step: 5,
    min: undefined,
    max: undefined,
    value: '5',
    sanitized: '5',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'range',
    step: 5,
    min: undefined,
    max: undefined,
    value: '7',
    sanitized: '5',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'range',
    step: 5,
    min: undefined,
    max: undefined,
    value: '10',
    sanitized: '10',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'range',
    step: 25,
    min: 0,
    max: undefined,
    value: '0',
    sanitized: '0',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'range',
    step: 25,
    min: 0,
    max: undefined,
    value: '25',
    sanitized: '25',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'range',
    step: 25,
    min: 0,
    max: undefined,
    value: '30',
    sanitized: '25',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'range',
    step: 25,
    min: 0,
    max: undefined,
    value: '50',
    sanitized: '50',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'range',
    step: 'any',
    min: undefined,
    max: undefined,
    value: '7',
    sanitized: '7',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'range',
    step: 'any',
    min: undefined,
    max: undefined,
    value: '13',
    sanitized: '13',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 7,
    min: undefined,
    max: undefined,
    value: '1970-01-01',
    sanitized: '1970-01-01',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 7,
    min: undefined,
    max: undefined,
    value: '1970-01-08',
    sanitized: '1970-01-08',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 7,
    min: undefined,
    max: undefined,
    value: '2026-08-13',
    sanitized: '2026-08-13',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 7,
    min: undefined,
    max: undefined,
    value: '2026-08-16',
    sanitized: '2026-08-16',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 7,
    min: undefined,
    max: undefined,
    value: '2026-08-20',
    sanitized: '2026-08-20',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 1,
    min: undefined,
    max: undefined,
    value: '2026-08-16',
    sanitized: '2026-08-16',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 1,
    min: undefined,
    max: undefined,
    value: '2026-02-30',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 1,
    min: undefined,
    max: undefined,
    value: 'not-a-date',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 1,
    min: undefined,
    max: undefined,
    value: '',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 7,
    min: '2026-08-16',
    max: undefined,
    value: '2026-08-16',
    sanitized: '2026-08-16',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 7,
    min: '2026-08-16',
    max: undefined,
    value: '2026-08-23',
    sanitized: '2026-08-23',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 7,
    min: '2026-08-16',
    max: undefined,
    value: '2026-08-17',
    sanitized: '2026-08-17',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 7,
    min: '2026-08-16',
    max: undefined,
    value: '2026-08-09',
    sanitized: '2026-08-09',
    mismatch: false,
    underflow: true,
    overflow: false
  },
  {
    type: 'date',
    step: 2,
    min: undefined,
    max: undefined,
    value: '1970-01-01',
    sanitized: '1970-01-01',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 2,
    min: undefined,
    max: undefined,
    value: '1970-01-02',
    sanitized: '1970-01-02',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 2,
    min: undefined,
    max: undefined,
    value: '1970-01-03',
    sanitized: '1970-01-03',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 'any',
    min: undefined,
    max: undefined,
    value: '2026-08-17',
    sanitized: '2026-08-17',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 30,
    min: '2026-01-01',
    max: undefined,
    value: '2026-01-01',
    sanitized: '2026-01-01',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 30,
    min: '2026-01-01',
    max: undefined,
    value: '2026-01-31',
    sanitized: '2026-01-31',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: 30,
    min: '2026-01-01',
    max: undefined,
    value: '2026-01-15',
    sanitized: '2026-01-15',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 3,
    min: undefined,
    max: undefined,
    value: '1970-01',
    sanitized: '1970-01',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 3,
    min: undefined,
    max: undefined,
    value: '1970-04',
    sanitized: '1970-04',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 3,
    min: undefined,
    max: undefined,
    value: '1970-02',
    sanitized: '1970-02',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 3,
    min: undefined,
    max: undefined,
    value: '2026-07',
    sanitized: '2026-07',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 3,
    min: undefined,
    max: undefined,
    value: '2026-08',
    sanitized: '2026-08',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 3,
    min: undefined,
    max: undefined,
    value: '2026-10',
    sanitized: '2026-10',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 1,
    min: undefined,
    max: undefined,
    value: '2026-08',
    sanitized: '2026-08',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 1,
    min: undefined,
    max: undefined,
    value: '2026-13',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 1,
    min: undefined,
    max: undefined,
    value: '',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 6,
    min: '2026-02',
    max: undefined,
    value: '2026-02',
    sanitized: '2026-02',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 6,
    min: '2026-02',
    max: undefined,
    value: '2026-08',
    sanitized: '2026-08',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 6,
    min: '2026-02',
    max: undefined,
    value: '2026-03',
    sanitized: '2026-03',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 12,
    min: undefined,
    max: undefined,
    value: '1970-01',
    sanitized: '1970-01',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 12,
    min: undefined,
    max: undefined,
    value: '2026-01',
    sanitized: '2026-01',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: 12,
    min: undefined,
    max: undefined,
    value: '2026-02',
    sanitized: '2026-02',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 2,
    min: undefined,
    max: undefined,
    value: '1970-W01',
    sanitized: '1970-W01',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 2,
    min: undefined,
    max: undefined,
    value: '1970-W02',
    sanitized: '1970-W02',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 2,
    min: undefined,
    max: undefined,
    value: '1970-W03',
    sanitized: '1970-W03',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 2,
    min: undefined,
    max: undefined,
    value: '2026-W33',
    sanitized: '2026-W33',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 2,
    min: undefined,
    max: undefined,
    value: '2026-W34',
    sanitized: '2026-W34',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 1,
    min: undefined,
    max: undefined,
    value: '2026-W01',
    sanitized: '2026-W01',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 1,
    min: undefined,
    max: undefined,
    value: '2026-W53',
    sanitized: '2026-W53',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 1,
    min: undefined,
    max: undefined,
    value: '2020-W53',
    sanitized: '2020-W53',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 1,
    min: undefined,
    max: undefined,
    value: '2026-W00',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 1,
    min: undefined,
    max: undefined,
    value: '',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 4,
    min: '2026-W05',
    max: undefined,
    value: '2026-W05',
    sanitized: '2026-W05',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 4,
    min: '2026-W05',
    max: undefined,
    value: '2026-W09',
    sanitized: '2026-W09',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: 4,
    min: '2026-W05',
    max: undefined,
    value: '2026-W06',
    sanitized: '2026-W06',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 900,
    min: undefined,
    max: undefined,
    value: '00:00',
    sanitized: '00:00',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 900,
    min: undefined,
    max: undefined,
    value: '00:15',
    sanitized: '00:15',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 900,
    min: undefined,
    max: undefined,
    value: '00:30',
    sanitized: '00:30',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 900,
    min: undefined,
    max: undefined,
    value: '00:10',
    sanitized: '00:10',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 900,
    min: undefined,
    max: undefined,
    value: '13:45',
    sanitized: '13:45',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 900,
    min: undefined,
    max: undefined,
    value: '13:50',
    sanitized: '13:50',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 1,
    min: undefined,
    max: undefined,
    value: '13:45:30',
    sanitized: '13:45:30',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 1,
    min: undefined,
    max: undefined,
    value: '13:45',
    sanitized: '13:45',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 1,
    min: undefined,
    max: undefined,
    value: '13:45:30.500',
    sanitized: '13:45:30.500',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 60,
    min: undefined,
    max: undefined,
    value: '13:45',
    sanitized: '13:45',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 60,
    min: undefined,
    max: undefined,
    value: '13:45:30',
    sanitized: '13:45:30',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 1800,
    min: '09:00',
    max: undefined,
    value: '09:00',
    sanitized: '09:00',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 1800,
    min: '09:00',
    max: undefined,
    value: '09:30',
    sanitized: '09:30',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 1800,
    min: '09:00',
    max: undefined,
    value: '09:15',
    sanitized: '09:15',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 1800,
    min: '09:00',
    max: undefined,
    value: '10:00',
    sanitized: '10:00',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 'any',
    min: undefined,
    max: undefined,
    value: '13:45:30.123',
    sanitized: '13:45:30.123',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 0.5,
    min: undefined,
    max: undefined,
    value: '13:45:30.500',
    sanitized: '13:45:30.500',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 0.5,
    min: undefined,
    max: undefined,
    value: '13:45:30.250',
    sanitized: '13:45:30.250',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 1,
    min: undefined,
    max: undefined,
    value: '25:00',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 1,
    min: undefined,
    max: undefined,
    value: 'nope',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: 1,
    min: undefined,
    max: undefined,
    value: '',
    sanitized: '',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: 900,
    min: undefined,
    max: undefined,
    value: '2026-08-16T00:00',
    sanitized: '2026-08-16T00:00',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: 900,
    min: undefined,
    max: undefined,
    value: '2026-08-16T00:15',
    sanitized: '2026-08-16T00:15',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: 900,
    min: undefined,
    max: undefined,
    value: '2026-08-16T00:10',
    sanitized: '2026-08-16T00:10',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: 60,
    min: undefined,
    max: undefined,
    value: '2026-08-16T13:45',
    sanitized: '2026-08-16T13:45',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: 60,
    min: undefined,
    max: undefined,
    value: '2026-08-16T13:45:30',
    sanitized: '2026-08-16T13:45:30',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: 1,
    min: undefined,
    max: undefined,
    value: '2026-08-16T13:45:30',
    sanitized: '2026-08-16T13:45:30',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: 1,
    min: undefined,
    max: undefined,
    value: '2026-08-16T13:45:30.500',
    sanitized: '2026-08-16T13:45:30.5',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: 3600,
    min: '2026-08-16T00:30',
    max: undefined,
    value: '2026-08-16T00:30',
    sanitized: '2026-08-16T00:30',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: 3600,
    min: '2026-08-16T00:30',
    max: undefined,
    value: '2026-08-16T01:30',
    sanitized: '2026-08-16T01:30',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: 3600,
    min: '2026-08-16T00:30',
    max: undefined,
    value: '2026-08-16T01:00',
    sanitized: '2026-08-16T01:00',
    mismatch: true,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: undefined,
    min: '2026-01-10',
    max: '2026-01-20',
    value: '2026-01-09',
    sanitized: '2026-01-09',
    mismatch: false,
    underflow: true,
    overflow: false
  },
  {
    type: 'date',
    step: undefined,
    min: '2026-01-10',
    max: '2026-01-20',
    value: '2026-01-10',
    sanitized: '2026-01-10',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: undefined,
    min: '2026-01-10',
    max: '2026-01-20',
    value: '2026-01-20',
    sanitized: '2026-01-20',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'date',
    step: undefined,
    min: '2026-01-10',
    max: '2026-01-20',
    value: '2026-01-21',
    sanitized: '2026-01-21',
    mismatch: false,
    underflow: false,
    overflow: true
  },
  {
    type: 'month',
    step: undefined,
    min: '2026-02',
    max: '2026-12',
    value: '2026-01',
    sanitized: '2026-01',
    mismatch: false,
    underflow: true,
    overflow: false
  },
  {
    type: 'month',
    step: undefined,
    min: '2026-02',
    max: '2026-12',
    value: '2026-02',
    sanitized: '2026-02',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: undefined,
    min: '2026-02',
    max: '2026-12',
    value: '2026-12',
    sanitized: '2026-12',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'month',
    step: undefined,
    min: '2026-02',
    max: '2026-12',
    value: '2027-01',
    sanitized: '2027-01',
    mismatch: false,
    underflow: false,
    overflow: true
  },
  {
    type: 'week',
    step: undefined,
    min: '2026-W05',
    max: '2026-W40',
    value: '2026-W04',
    sanitized: '2026-W04',
    mismatch: false,
    underflow: true,
    overflow: false
  },
  {
    type: 'week',
    step: undefined,
    min: '2026-W05',
    max: '2026-W40',
    value: '2026-W05',
    sanitized: '2026-W05',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: undefined,
    min: '2026-W05',
    max: '2026-W40',
    value: '2026-W40',
    sanitized: '2026-W40',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'week',
    step: undefined,
    min: '2026-W05',
    max: '2026-W40',
    value: '2026-W41',
    sanitized: '2026-W41',
    mismatch: false,
    underflow: false,
    overflow: true
  },
  {
    type: 'time',
    step: undefined,
    min: '09:00',
    max: '17:00',
    value: '08:59',
    sanitized: '08:59',
    mismatch: false,
    underflow: true,
    overflow: false
  },
  {
    type: 'time',
    step: undefined,
    min: '09:00',
    max: '17:00',
    value: '09:00',
    sanitized: '09:00',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: undefined,
    min: '09:00',
    max: '17:00',
    value: '17:00',
    sanitized: '17:00',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'time',
    step: undefined,
    min: '09:00',
    max: '17:00',
    value: '17:01',
    sanitized: '17:01',
    mismatch: false,
    underflow: false,
    overflow: true
  },
  {
    type: 'datetime-local',
    step: undefined,
    min: '2026-01-10T09:00',
    max: '2026-01-10T17:00',
    value: '2026-01-10T08:59',
    sanitized: '2026-01-10T08:59',
    mismatch: false,
    underflow: true,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: undefined,
    min: '2026-01-10T09:00',
    max: '2026-01-10T17:00',
    value: '2026-01-10T09:00',
    sanitized: '2026-01-10T09:00',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: undefined,
    min: '2026-01-10T09:00',
    max: '2026-01-10T17:00',
    value: '2026-01-10T17:00',
    sanitized: '2026-01-10T17:00',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'datetime-local',
    step: undefined,
    min: '2026-01-10T09:00',
    max: '2026-01-10T17:00',
    value: '2026-01-10T17:01',
    sanitized: '2026-01-10T17:01',
    mismatch: false,
    underflow: false,
    overflow: true
  },
  {
    type: 'text',
    step: 5,
    min: undefined,
    max: undefined,
    value: '7',
    sanitized: '7',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'text',
    step: 5,
    min: undefined,
    max: undefined,
    value: 'abc',
    sanitized: 'abc',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'email',
    step: 5,
    min: undefined,
    max: undefined,
    value: 'a@b.com',
    sanitized: 'a@b.com',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'checkbox',
    step: 5,
    min: undefined,
    max: undefined,
    value: '7',
    sanitized: '7',
    mismatch: false,
    underflow: false,
    overflow: false
  },
  {
    type: 'password',
    step: 3,
    min: undefined,
    max: undefined,
    value: '7',
    sanitized: '7',
    mismatch: false,
    underflow: false,
    overflow: false
  }
];
